### ISSUE TITLE
Falsche Verlinkung bzw. Modul erscheint nicht mehr 

### ISSUE THREAD

**Issue by hatzisan** [sedlareg/umami-nation-order-system#6]
![image](https://user-images.githubusercontent.com/29704841/27535107-a6ca8d4a-5a69-11e7-8b22-41a7b7ebfa30.png)
Wenn ich eine Bestellung abschliesse - sprich rechts unten auf "Bestellung abschliesse" klicke dann komm ich auf eine Folgeseite in der das eigentliche Bestellinterface "Bestellungen" oben fehlt (das Ding mit den einzelnen Produkten)

![image](https://user-images.githubusercontent.com/29704841/27535123-c0d850aa-5a69-11e7-9b67-d07e77b2e59e.png)

**Comment by sedlareg** [comment]
jo wird mit dem neuesten bugfix erledigt
