### ISSUE TITLE
IMPROVEMENT // Buttons evtl. größer machen

### ISSUE THREAD

**Issue by hatzisan** [sedlareg/umami-nation-order-system#7]
![image](https://user-images.githubusercontent.com/29704841/27535467-41cb806e-5a6b-11e7-90c3-4a7092158575.png)

Wenn es kein Stress ist wäre es gut wenn die Buttons "Bestellung abschliessen" größer wären

**Comment by sedlareg** [comment]
jo kein problem... ✔️
