### ISSUE TITLE
IMPROVEMENT // Buttongröße und Farbe #enhancement

### ISSUE THREAD

**Issue by hatzisan** [sedlareg/umami-nation-order-system#8]
![image](https://user-images.githubusercontent.com/29704841/27535589-d31addc6-5a6b-11e7-9892-6049c61e7ccc.png)

So und nochmal so Kleinscheiss - auch hier wäre es cool wenn der Button noch etwas größer wäre. In der Hitze des Gefechts dann einfacher zu treffen. 
Auch wäre es gut wenn die Farben der Buttons nach dem Statuswechsel von "herstellen" zu "Produkt fertig" sich farblich mehr unterscheiden würden....z.b. Grün und blau oder grün und rot

**Comment by sedlareg** [comment]
farbe geändert ✔️ 
größe geändert ✔️
